name: 'Deploy with Terraform'

on:
  push:
    branches:
    - main
  pull_request:

env:
  GOOGLE_APPLICATION_CREDENTIALS: /credentials.json

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Setup Credentials
      run: echo ${{ secrets.TF_GOOGLE_CREDENTIALS }} | base64 -d > /credentials.json

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Generate the function archives
      run: cd feeds/pypi; zip pypi.zip *; cd ../../;

    - name: Terraform Plan
      run: terraform plan

      # On push to main, build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
